### ISSUE TITLE
URL for driver not available

### ISSUE THREAD

**Issue by JBalanza** [gabriellandau/EDRSandblast-GodFault#1]
Hi, The link to download the vulnerable driver RTCore64.sys at Readme is available, but the driver is not within the downloaded ZIP file.

As an example, the driver can be downloaded here https://www.loldrivers.io/drivers/e32bc3da-4db1-4858-a62c-6fbe4db6afbd/

**Comment by gabriellandau** [comment]
This project doesn't use any drivers.  It exploits the vulnerable kernel itself using the unpatched [GodFault exploit chain](https://github.com/gabriellandau/PPLFault), instead of any third-party vulnerable drivers. 

If you want to use vulnerable drivers instead, I'd suggest using the [original EDRSandblast tool](https://github.com/wavestone-cdt/EDRSandblast).  Be aware that you may have issues on new (non-upgrade) Win11 22H2 installs due to the [Vulnerable Driver Blocklist](https://learn.microsoft.com/en-us/windows/security/application-security/application-control/windows-defender-application-control/design/microsoft-recommended-driver-block-rules#vulnerable-driver-blocklist-xml).

By the way, `RTCore64.sys` **is** in the zip file.  Open `MSIAfterburnerSetup462Beta2.exe` with 7-zip.

![image](https://github.com/gabriellandau/EDRSandblast-GodFault/assets/42078554/b0c85485-f149-431b-bcaf-3a59c07d5d7a)
